version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: snapit-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/snapit
      - JWT_SECRET=your-jwt-secret
      - CLOUDINARY_CLOUD_NAME=your-cloudinary-name
      - CLOUDINARY_API_KEY=your-cloudinary-key
      - CLOUDINARY_API_SECRET=your-cloudinary-secret
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: snapit-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # MongoDB Database
  mongo:
    image: mongo:6.0
    container_name: snapit-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongo_data:
